[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "trello"
version = "2.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Boards", "Lists", "Workflows", "Vendor/Trello", "Area/Project Management", "Type/Connector"]
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-trello"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
