[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "trello"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Trello", "Boards", "Lists", "Cards"] # TODO: Add keywords
# icon = "/home/sashenkag/bal_connector/module-ballerinax-trello/docs/setup/resources/trello-logo.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-trello"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
